[package]
name = "jamendo"
version = "0.1.0"
authors = ["Jakob Gillich <jakob@gillich.me>"]
license = "MIT"

[dependencies]
serde = "0.7"
serde_json = "0.7"
serde_macros = "0.7"
hyper = { version = "0.9", features = [ "serde-serialization" ] }
url = "1.0"
